//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class goPhoto
    {
        public System.DateTime Date { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string middleName { get; set; }
    }
}
